# Generated by Django 6.0.7 on 2026-07-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetimer',
            name='planned_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('', 'closed by the user'), ('planned_end', 'planned duration exhausted'), ('idle_timeout', 'no response to reminders')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='estimated_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
