# Generated by Django 6.0.7 on 2026-07-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_activetimer_planned_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetimer',
            name='confirmed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activetimer',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetimer',
            name='reminder_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='idle_threshold_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='reminder_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
