# Generated by Django 6.0.7 on 2026-08-04 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('coach', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_variants', models.JSONField(blank=True, default=list)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('lats', 'Lats'), ('upper_back', 'Upper back'), ('traps', 'Traps'), ('front_delts', 'Front delts'), ('lateral_delts', 'Lateral delts'), ('rear_delts', 'Rear delts'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('abductors', 'Abductors'), ('adductors', 'Adductors'), ('calves', 'Calves'), ('lower_back', 'Lower back'), ('abs', 'Abs')], db_index=True, max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('movement_pattern', models.CharField(blank=True, choices=[('horizontal_push', 'Horizontal push'), ('vertical_push', 'Vertical push'), ('horizontal_pull', 'Horizontal pull'), ('vertical_pull', 'Vertical pull'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('lunge', 'Lunge'), ('isolation', 'Isolation')], max_length=20)),
                ('is_unilateral', models.BooleanField(default=False)),
                ('setting', models.CharField(choices=[('home', 'At home'), ('gym', 'At the gym')], db_index=True, max_length=4)),
                ('introduced_by_user_substitution', models.BooleanField(default=False)),
                ('exercisedb_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('preview_gif', models.FileField(blank=True, upload_to='exercise_gifs/')),
                ('needs_review', models.JSONField(blank=True, default=list)),
                ('equipment_required', models.ManyToManyField(blank=True, related_name='exercises', to='training.equipment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('series_label', models.CharField(blank=True, max_length=2)),
                ('series_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('coach_annotation', models.TextField(blank=True)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('days_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='training.program')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('weeks_count', models.PositiveSmallIntegerField()),
                ('weeks_declared_in_source', models.BooleanField(default=True)),
                ('number_inferred', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='training.programvariant')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SetPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('target_reps_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_reps_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_failure', models.BooleanField(default=False)),
                ('hold_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_per_side', models.BooleanField(default=False)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest_role', models.CharField(choices=[('between_sets', 'Between sets'), ('superset_transition', 'Superset transition'), ('superset_round_end', 'Superset round end')], max_length=24)),
                ('tempo', models.CharField(blank=True, max_length=9)),
                ('is_backoff_set', models.BooleanField(default=False)),
                ('cluster_reps', models.JSONField(blank=True, null=True)),
                ('reps_raw', models.CharField(blank=True, max_length=60)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.exerciseslot')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('weight_unit', models.CharField(default='kg', max_length=3)),
                ('active_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.programvariant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_deload', models.BooleanField(default=False)),
                ('is_synthesised', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.phase')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(blank=True, max_length=12)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.week')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='exerciseslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='training.workoutday'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('performed_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('imported_from', models.CharField(blank=True, db_index=True, max_length=40)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.workoutday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_substituted', models.BooleanField(default=False)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_basis', models.CharField(choices=[('total', 'Total weight'), ('per_dumbbell', 'Per dumbbell'), ('bodyweight', 'Bodyweight'), ('added', 'Weight added to bodyweight')], default='total', max_length=14)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imported_from', models.CharField(blank=True, max_length=40)),
                ('import_note', models.TextField(blank=True)),
                ('performed_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.setprescription')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='training.workoutsession')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('session', 'This session only'), ('program', 'Whole program')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='training.exerciseslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'program'], name='training_pr_user_id_dca3f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'program'), name='uniq_program_access')],
            },
        ),
        migrations.AddConstraint(
            model_name='programvariant',
            constraint=models.UniqueConstraint(fields=('program', 'slug'), name='uniq_variant'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('variant', 'number'), name='uniq_phase'),
        ),
        migrations.AddConstraint(
            model_name='setprescription',
            constraint=models.UniqueConstraint(fields=('slot', 'set_number'), name='uniq_set'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['phase', 'number'], name='training_we_phase_i_e309cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('phase', 'number'), name='uniq_week'),
        ),
        migrations.AddConstraint(
            model_name='workoutday',
            constraint=models.UniqueConstraint(fields=('week', 'order'), name='uniq_day'),
        ),
        migrations.AddConstraint(
            model_name='exerciseslot',
            constraint=models.UniqueConstraint(fields=('day', 'order'), name='uniq_slot'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-performed_on'], name='training_wo_user_id_6f369e_idx'),
        ),
        migrations.AddIndex(
            model_name='setlog',
            index=models.Index(fields=['performed_exercise', '-id'], name='training_se_perform_30ca56_idx'),
        ),
    ]
