# Generated by Django 6.0.7 on 2026-08-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_runs_from_active_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': [models.OrderBy(models.F('performed_on'), descending=True, nulls_last=True), '-id']},
        ),
    ]
